import type { SourceRoutingCapabilityProfile } from "./source-routing.schemas";

const profile = (sourceKey: string, values: Omit<SourceRoutingCapabilityProfile, "sourceKey">): SourceRoutingCapabilityProfile => ({ sourceKey, ...values });

export const sourceRoutingCapabilityProfiles: Record<string, SourceRoutingCapabilityProfile> = {
  fixture: profile("fixture", {
    supports_software_demand: 1,
    supports_consumer_demand: 1,
    supports_developer_demand: 1,
    supports_ecommerce_demand: 1,
    supports_local_demand: 1,
    supports_switching_intent: 1,
    supports_recommendation_intent: 1,
    supports_problem_discussion: 1,
    supports_feature_discussion: 1,
    supports_competitor_comparison: 1,
    supports_long_form_context: 1,
    supports_replies: 1,
    supports_recency: 1,
    cost_class: "free_low",
  }),
  "hacker-news": profile("hacker-news", {
    supports_software_demand: 0.9,
    supports_consumer_demand: 0.35,
    supports_developer_demand: 0.95,
    supports_ecommerce_demand: 0.15,
    supports_local_demand: 0.05,
    supports_switching_intent: 0.55,
    supports_recommendation_intent: 0.5,
    supports_problem_discussion: 0.85,
    supports_feature_discussion: 0.8,
    supports_competitor_comparison: 0.6,
    supports_long_form_context: 0.95,
    supports_replies: 0.8,
    supports_recency: 0.7,
    cost_class: "free_low",
  }),
  bluesky: profile("bluesky", {
    supports_software_demand: 0.55,
    supports_consumer_demand: 0.6,
    supports_developer_demand: 0.35,
    supports_ecommerce_demand: 0.35,
    supports_local_demand: 0.2,
    supports_switching_intent: 0.5,
    supports_recommendation_intent: 0.55,
    supports_problem_discussion: 0.55,
    supports_feature_discussion: 0.4,
    supports_competitor_comparison: 0.35,
    supports_long_form_context: 0.35,
    supports_replies: 0.7,
    supports_recency: 0.9,
    cost_class: "free_low",
  }),
  reddit: profile("reddit", {
    supports_software_demand: 0.9,
    supports_consumer_demand: 0.9,
    supports_developer_demand: 0.75,
    supports_ecommerce_demand: 0.85,
    supports_local_demand: 0.6,
    supports_switching_intent: 0.9,
    supports_recommendation_intent: 0.9,
    supports_problem_discussion: 0.95,
    supports_feature_discussion: 0.8,
    supports_competitor_comparison: 0.85,
    supports_long_form_context: 0.8,
    supports_replies: 0.95,
    supports_recency: 0.7,
    cost_class: "free_rate_limited",
  }),
  github: profile("github", {
    supports_software_demand: 0.9,
    supports_consumer_demand: 0.15,
    supports_developer_demand: 1,
    supports_ecommerce_demand: 0.08,
    supports_local_demand: 0.03,
    supports_switching_intent: 0.45,
    supports_recommendation_intent: 0.35,
    supports_problem_discussion: 0.8,
    supports_feature_discussion: 0.95,
    supports_competitor_comparison: 0.45,
    supports_long_form_context: 0.7,
    supports_replies: 0.6,
    supports_recency: 0.75,
    cost_class: "free_rate_limited",
  }),
  x: profile("x", {
    supports_software_demand: 0.8,
    supports_consumer_demand: 0.85,
    supports_developer_demand: 0.65,
    supports_ecommerce_demand: 0.8,
    supports_local_demand: 0.35,
    supports_switching_intent: 0.9,
    supports_recommendation_intent: 0.85,
    supports_problem_discussion: 0.8,
    supports_feature_discussion: 0.7,
    supports_competitor_comparison: 0.8,
    supports_long_form_context: 0.35,
    supports_replies: 0.75,
    supports_recency: 1,
    cost_class: "paid_medium",
  }),
};

export const sourceRoutingSourceKeys = Object.keys(sourceRoutingCapabilityProfiles);
